# Generated by Django 4.2.11 on 2024-04-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_carritocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
