# Generated by Django 4.2.11 on 2024-04-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_venta_fecha_venta_fecha_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total_acumulado',
        ),
    ]
